// <auto-generated />
namespace EF_CF_Approach_Demo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Dbcreation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Dbcreation));
        
        string IMigrationMetadata.Id
        {
            get { return "202203300511501_Dbcreation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
